apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
data:
  airflow.cfg: |    
    [core]
    colored_console_log = False
    dags_folder = /opt/airflow/dags
    executor = KubernetesExecutor
    load_examples = False
    dags_are_paused_at_creation = True
    expose_config = True
    
    [kubernetes_executor]
    namespace = airflow
    worker_container_repository = local-airflow-image
    worker_container_tag =
    pod_template_file = /opt/airflow/pod-template-local.yaml
    multi_namespace_mode = False
    delete_worker_pods = True
    delete_worker_pods_on_failure = False
    
    [logging]
    colored_console_log = False
    remote_logging = False
    base_log_folder = /opt/airflow/logs
    logging_level = INFO
    
    [metrics]
    statsd_host = airflow-statsd
    statsd_on = False
    statsd_port = 9125
    statsd_prefix = airflow
    
    [scheduler]
    catch_up_by_default = False
    run_duration = 41460
    standalone_dag_processor = False
    statsd_host = airflow-statsd
    statsd_on = True
    statsd_port = 9125
    statsd_prefix = airflow
    
    [webserver]
    enable_proxy_fix = True
    rbac = False
    authenticate = False
    auto_refresh_interval = 10

    [api]
    auth_backends = airflow.api.auth.backend.default
