apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: airflow
resources:
  - config-airflow.yaml
  - namespace.yaml
  - ../../services/airflow-scheduler
  - ../../services/airflow-webserver
  - ../../services/airflow-workers
  - ../../services/postgres
  - ../../services/rbac

patchesStrategicMerge:
  - scheduler-deployment.yaml
  - webserver-deployment.yaml