kind: Deployment
apiVersion: apps/v1
metadata:
  name: airflow-scheduler
  labels:
    tier: airflow
    component: scheduler
    release: airflow
spec:
  template:
    spec:
      initContainers:
        - name: init-db
          imagePullPolicy: Always
          image: "063789902345.dkr.ecr.us-west-2.amazonaws.com/airflow:prod"
      containers:
        # Always run the main scheduler container.
        - name: scheduler
          imagePullPolicy: Always
          volumeMounts:
            - name: airflow-config
              mountPath: "/opt/airflow/airflow.cfg"
              subPath: airflow.cfg
              readOnly: true
          image: "063789902345.dkr.ecr.us-west-2.amazonaws.com/airflow:prod"
      volumes:
        - name: airflow-config
          configMap:
            name: airflow-config
