apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: airflow
resources:
- postgres-service.yaml
- postgres-deployment.yaml

configMapGenerator:
- name: postgres-config
  env: postgres.env

generatorOptions:
  disableNameSuffixHash: true
