apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: airflow
resources:
- pod-launcher-role.yaml
- pod-launcher-rolebinding.yaml
- pod-log-reader-role.yaml
- pod-log-reader-rolebinding.yaml
- airflow-serviceaccount.yaml

generatorOptions:
  disableNameSuffixHash: true
